import type { QAPair } from '../report/types.js';
import type { LLMClient } from '../llm/client.js';
import { getAllQuestionsSorted, CORE_QUESTIONS, type InterviewQuestion } from './questions.js';
import {
  INTERVIEW_SYSTEM_PROMPT,
  buildFollowUpPrompt,
  COMPLIANCE_FIELD_CHECKLIST,
  detectAdversarialClaim,
  buildAdversarialProbePrompt,
} from '../llm/prompts.js';

export interface InterviewProtocol {
  /** Get the next question to ask, or null if interview is complete */
  nextQuestion(): InterviewQuestion | null;

  /** Record an answer. Returns false if answer was skipped (greeting/repeat). */
  recordAnswer(question: InterviewQuestion, answer: string): boolean;

  /** Generate a follow-up question based on context and missing compliance fields */
  generateFollowUp(category: QAPair['category']): Promise<InterviewQuestion | null>;

  /** Get the full transcript so far */
  getTranscript(): QAPair[];

  /** Check if the interview is complete */
  isComplete(): boolean;

  /** Total number of core questions (excluding follow-ups) */
  totalCoreQuestions: number;

  /**
   * AAP-60 — set the internal follow-up counters to reflect a transcript
   * that was generated by a previous instance. Used by the stateless
   * tool-call question-planner during rehydration: without this, the
   * fresh protocol restarts both counters at zero on every
   * `submit_answer`, and the cap check inside `generateFollowUp` never
   * fires, so the planner produces follow-ups indefinitely.
   *
   * `perQuestion` keys are core-question IDs. Any ID not present
   * stays at zero.
   */
  primeFollowUpCounts(state: {
    global: number;
    perQuestion: Map<string, number>;
  }): void;
}

// ─── Greeting detection ──────────────────────────────────────────────────────

const GREETING_PATTERNS = [
  /^hi\b/i,
  /^hello\b/i,
  /^hey\b/i,
  /ready to answer/i,
  /ready for questions/i,
  /^i am ready/i,
  /^i'm ready/i,
  /let'?s begin/i,
  /let'?s start/i,
  /^greetings/i,
];

/** Detect if an answer is just a greeting with no substantive content */
export function isGreeting(answer: string): boolean {
  const trimmed = answer.trim();
  // Short answers that match greeting patterns
  if (trimmed.length > 200) return false; // Long answers aren't greetings
  return GREETING_PATTERNS.some(p => p.test(trimmed));
}

// ─── Stale / off-topic answer detection ─────────────────────────────────────

/** Topic keywords per compliance field — used to detect answers to the wrong question */
const TOPIC_SIGNALS: Record<string, RegExp[]> = {
  agentProfile: [
    /\bproject.?name\b/i, /\bowner\b/i, /\btrigger/i, /\bwhat I (do|specifically)\b/i,
  ],
  systemId: [
    /\b(→|->)\s*(REST|API|OAuth|SDK|Bot)\b/i, /\bconnect to\b/i, /\bsystems?\s+I\b/i,
  ],
  scopesRequested: [
    /\boauth\s*scop/i, /\bgoogleapis\.com\/auth\//i, /\b(readonly|readwrite|\.edit|\.send|\.admin)\b/i,
  ],
  dataSensitivity: [
    /\b(PII|financial|credentials|confidential|non.?sensitive)\b/i, /\bclassif(y|ied)\b/i,
  ],
  writeOperations: [
    /\b(→|->)\s*(Yes|No)\s*(→|->)/i, /\b(append|insert|create|delete)\s*(row|record|spreadsheet|message)/i,
    /\bvolume\/day\b/i,
  ],
  blastRadius: [
    /\b(worst.?case|single.?record|single.?user|cross.?tenant|org.?wide)\b/i,
    /\bcan it be (undone|recovered)\b/i,
  ],
  frequencyAndVolume: [
    /\b(times?\s+per|runs?\s+per|calls?\s+per|\/week|\/day)\b/i, /\bbatch\s+size\b/i,
  ],
  scopesDelta: [
    /\bnever\s+(actually\s+)?used\b/i, /\bsafely\s+(be\s+)?revoked\b/i, /\bunused\s+permission/i,
  ],
  riskAssessment: [
    /\bworst\s+realistic\s+failure\b/i, /\bwho\s+is\s+affected\b/i, /\bhow\s+bad\s+is\s+the\s+damage\b/i,
    /\bcan\s+it\s+be\s+recovered\b/i,
  ],
};

/**
 * Detect if an answer is clearly responding to a different question (stale session).
 * Returns true if the answer strongly matches a DIFFERENT question's topic
 * but has no relevance to the current question.
 *
 * Conservative: only triggers on long answers (300+ chars) that match 2+ signals
 * from a different topic AND zero signals from the current topic. Skips Q1 entirely
 * since first answers are too varied to classify reliably.
 */
export function isStaleAnswer(question: InterviewQuestion, answer: string): boolean {
  if (answer.length < 300) return false; // Only check long, detailed answers
  const currentField = question.complianceField;
  if (!currentField) return false;

  // Never flag Q1 (agentProfile) — first answers are too varied
  if (currentField === 'agentProfile') return false;

  const currentSignals = TOPIC_SIGNALS[currentField] ?? [];
  const matchesCurrent = currentSignals.some(p => p.test(answer));

  // If the answer matches the current question's topic at all, it's not stale
  if (matchesCurrent) return false;

  // Check if it strongly matches a different question's topic (need 3+ signals)
  let strongOtherMatch = false;
  for (const [field, signals] of Object.entries(TOPIC_SIGNALS)) {
    if (field === currentField) continue;
    const matches = signals.filter(p => p.test(answer)).length;
    if (matches >= 3) { strongOtherMatch = true; break; }
  }

  return strongOtherMatch;
}

// ─── Vagueness detection ─────────────────────────────────────────────────────

/** Vagueness indicators — if an answer matches these patterns, it needs a follow-up */
const VAGUE_PATTERNS = [
  /\b(the database|a database|some database)\b/i,
  /\b(read and write|read\/write|full access)\b/i,
  /\b(user data|some data|the data)\b/i,
  /\b(regularly|periodically|sometimes|occasionally|as needed|when needed)\b/i,
  /\b(could affect|might affect|may affect)\b/i,
  /\b(various|several|multiple|many|some)\s+(systems?|apis?|services?|databases?)/i,
  /\b(everything|all access|full permissions?)\b/i,
  /\bi[' ']?m not sure\b/i,
  /\bnot sure\b/i,
  /\bi don[' ']?t know\b/i,
  // Hedging language — agent describes theoretical capabilities, not actual behavior
  /\bi may (also )?(read|write|access|connect|use|modify|create|delete)\b/i,
  /\bwhen enabled\b/i,
  /\bif the task (requires|involves|needs)\b/i,
  /\bwhen (available|needed|required|the workflow)\b/i,
  /\b(can include|could include|may include)\b/i,
  /\baccess is (environment|session|task).dependent\b/i,
  /\bdepending on (the )?task\b/i,
  /\bconnectors? (are |is )?enabled\b/i,
  // Generic tool descriptions instead of specific project usage
  /\b(local workspace|active workspace|working directory)\b/i,
  /\bconnected (development )?tools\b/i,
];

/** Detect if an answer is too vague for compliance-grade reporting */
export function isVagueAnswer(answer: string): boolean {
  return VAGUE_PATTERNS.some(p => p.test(answer));
}

// ─── Repeated answer detection ───────────────────────────────────────────────

/** Normalize answer text for comparison (trim, lowercase, collapse whitespace) */
function normalizeForComparison(text: string): string {
  return text.trim().toLowerCase().replace(/\s+/g, ' ');
}

/** Check if an answer is a repeat of a previous answer */
function isRepeatedAnswer(answer: string, transcript: QAPair[]): boolean {
  if (transcript.length === 0) return false;
  const normalized = normalizeForComparison(answer);
  // Check for exact or near-exact repeats
  return transcript.some(qa => {
    const prevNormalized = normalizeForComparison(qa.answer);
    // Exact match or >90% overlap (handles minor variations)
    return normalized === prevNormalized ||
      (normalized.length > 50 && prevNormalized.includes(normalized.slice(0, normalized.length * 0.9 | 0)));
  });
}

// ─── Missing compliance fields ───────────────────────────────────────────────

/** Check which compliance fields are missing from the transcript for a given category */
function findMissingFields(transcript: QAPair[]): string[] {
  const allText = transcript.map(qa => qa.answer.toLowerCase()).join(' ');
  const missing: string[] = [];

  // Check for specific system identifiers
  if (!/\b(api|oauth|sdk|via|using)\b/i.test(allText)) {
    missing.push('systemId (specific API names, auth methods)');
  }

  // Check for specific scopes
  if (!/\b(scope|permission|role|\.readonly|\.send|\.modify|\.admin)\b/i.test(allText)) {
    missing.push('scopesRequested (specific OAuth scopes, API permissions)');
  }

  // Check for data sensitivity classification
  if (!/\b(pii|sensitive|confidential|financial|personal|classified)\b/i.test(allText)) {
    missing.push('dataSensitivity (PII, financial, confidential classification)');
  }

  // Check for blast radius
  if (!/\b(single.?record|single.?user|team|org.?wide|cross.?tenant|mailbox|affected)\b/i.test(allText)) {
    missing.push('blastRadius (scope of impact: single-record/user/team/org-wide)');
  }

  // Check for frequency numbers
  if (!/\b(\d+\s*(times?|per|\/)\s*(day|hour|minute|week|session)|batch)\b/i.test(allText)) {
    missing.push('frequencyAndVolume (specific numbers: times/day, batch size)');
  }

  // Check for write reversibility
  if (!/\b(revers|rollback|undo|irrevers|cannot be undone|can be restored)\b/i.test(allText)) {
    missing.push('writeOperations.reversible (whether writes can be rolled back)');
  }

  return missing;
}

// ─── Most-recent core question lookup ────────────────────────────────────────

/**
 * AAP-77 — find the MOST RECENT core question in a given category by
 * scanning the transcript backward. Returns null if no core question
 * in that category has been asked yet.
 *
 * Why backward, not forward: `coreQuestions.find(...)` returns the first
 * core declared in the category, but the planner's follow-up bookkeeping
 * (in `primeFollowUpCounts` and the local increment below) attributes
 * follow-ups to the most-recently-asked core. If the cap check and the
 * increment touched different keys, the per-question cap (2 follow-ups
 * max) would never fire in categories with multiple core questions.
 *
 * Exported so the question-planner can share the same lookup logic and
 * stay byte-for-byte consistent with the cap check.
 */
export function findMostRecentCoreInCategory(
  category: QAPair['category'],
  transcript: QAPair[],
  coreQuestions: InterviewQuestion[],
): InterviewQuestion | null {
  // Index core questions by text for O(1) lookup during the backward scan.
  const coreByText = new Map<string, InterviewQuestion>();
  for (const c of coreQuestions) coreByText.set(c.text, c);

  for (let i = transcript.length - 1; i >= 0; i--) {
    const entry = transcript[i]!;
    if (entry.category !== category) continue;
    const core = coreByText.get(entry.question);
    if (core) return core;
  }
  return null;
}

// ─── Gap-topic ledger (AAP-146) ──────────────────────────────────────────────

/**
 * AAP-146 - session-level cap on how many times a single gap topic may be
 * re-probed across the WHOLE interview. Consistency probing (re-asking a
 * control from a different angle) is a legitimate audit technique, so we
 * CAP it rather than remove it: at most 3 asks per gap topic (the initial
 * ask plus 2 angles), regardless of which core question spawned the
 * follow-up. When the cap is hit the over-cap follow-up is dropped and the
 * gap stands as recorded (it already lands in findings via the normal
 * analysis path).
 *
 * Two live audits motivated this (sess-20260604-032116-fcece0 and
 * sess-20260610-035726-59fe71): 45+ questions where 58% circled two gaps
 * that were fully recorded after the first one or two asks.
 */
export const MAX_GAP_TOPIC_ASKS = 3;

/**
 * Two follow-up questions are the same gap topic when their normalized
 * content-word sets share at least GAP_TOPIC_MIN_SHARED words OR have
 * Jaccard >= GAP_TOPIC_JACCARD.
 *
 * Why two arms. The live evidence is varied phrasings of one gap: "walk me
 * through the concrete deletion flow", "what mechanism prevents deletion",
 * "what artifact confirms deletion completed". After stopwords those share
 * only the gap subject (e.g. {deletion, records}); Jaccard between them is
 * 0.08-0.20, well under 0.5, so a Jaccard-only rule would let every repeat
 * through. They DO reliably share 2+ content words (the gap nouns), and
 * measured against genuinely distinct gap topics (scopes, blast radius,
 * frequency) the shared-word count is 0. So shared-word count is the arm
 * that actually clusters the audit evidence; Jaccard is kept as a second
 * arm to also catch near-verbatim repeats of short questions where 2 shared
 * words might not appear but the overlap fraction is high.
 *
 * False-positive risk: two unrelated gaps that happen to share 2 longer
 * content words would be collapsed. Mitigated by stripping interrogation
 * scaffolding (TOPIC_STOPWORDS) so only gap-subject nouns survive, and by
 * the conservative length>3 filter. The audit data above shows distinct
 * topics share 0 words, so the practical risk is low; raising
 * GAP_TOPIC_MIN_SHARED to 3 would harden it further at the cost of letting
 * some 2-noun repeats through.
 */
const GAP_TOPIC_MIN_SHARED = 2;
const GAP_TOPIC_JACCARD = 0.5;

/**
 * A follow-up needs at least this many content words to be a re-probeable
 * gap TOPIC. Real audit gap probes always reference a subject (a system,
 * data type, or mechanism) and clear this easily: the live deletion /
 * escalation phrasings carry 5-8 content words. Anything thinner (a 1-2
 * word fragment) is not an identifiable gap and is exempt from the cap, so
 * the cap targets recurring audit subjects rather than incidental
 * two-word overlaps. Also keeps the GAP_TOPIC_MIN_SHARED=2 arm honest: a
 * sub-floor set could never legitimately share 2 of its words as a topic.
 */
const MIN_TOPIC_CONTENT_WORDS = 3;

/**
 * Content-word stopwords. Question scaffolding ("what", "concrete",
 * "agent", "specific") would otherwise dominate the overlap and make every
 * audit question look like every other. Stripped so the Jaccard score
 * reflects the gap SUBJECT (deletion, escalation, retention) rather than
 * the interrogation frame.
 */
const TOPIC_STOPWORDS = new Set<string>([
  'what', 'which', 'when', 'where', 'whom', 'whose', 'does', 'doesnt',
  'this', 'that', 'these', 'those', 'their', 'there', 'here', 'have',
  'would', 'could', 'should', 'will', 'with', 'within', 'into', 'onto',
  'from', 'your', 'youre', 'about', 'they', 'them', 'then', 'than',
  'each', 'every', 'some', 'such', 'into', 'over', 'under', 'upon',
  'concrete', 'concretely', 'specific', 'specifically', 'exactly',
  'actually', 'really', 'agent', 'deployment', 'question', 'answer',
  'walk', 'tell', 'describe', 'explain', 'provide', 'give', 'give',
  'using', 'used', 'uses', 'happen', 'happens', 'today', 'currently',
  'mention', 'mentioned', 'said', 'claim', 'claimed', 'example',
]);

/**
 * Reduce a follow-up question to its normalized content-word SET: lowercase,
 * letters only, length > 3, stopwords removed. Deterministic (no LLM, no
 * randomness) so the same question always maps to the same set and the cap
 * survives a server restart (the planner rebuilds the ledger from the
 * transcript). Returns a Set so callers can compute Jaccard directly.
 */
export function topicContentWords(text: string): Set<string> {
  const words = text
    .toLowerCase()
    .replace(/[^a-z\s]/g, ' ')
    .split(/\s+/)
    .filter(w => w.length > 3 && !TOPIC_STOPWORDS.has(w));
  return new Set(words);
}

/**
 * Decide whether two content-word sets describe the same gap topic. True
 * when they share at least GAP_TOPIC_MIN_SHARED words, or their Jaccard
 * meets GAP_TOPIC_JACCARD. Deterministic and symmetric. Empty sets never
 * match (a question with no content words has no identifiable topic).
 */
function sameTopic(a: Set<string>, b: Set<string>): boolean {
  if (a.size === 0 || b.size === 0) return false;
  let intersection = 0;
  for (const w of a) if (b.has(w)) intersection++;
  if (intersection >= GAP_TOPIC_MIN_SHARED) return true;
  const union = a.size + b.size - intersection;
  return union > 0 && intersection / union >= GAP_TOPIC_JACCARD;
}

interface TopicCluster {
  /** First phrasing seen in this cluster, used as the human-readable rep. */
  rep: string;
  /** Content-word sets of every member, for single-link membership tests. */
  members: Set<string>[];
}

/**
 * AAP-146 - group a list of follow-up texts into gap-topic clusters using
 * SINGLE-LINK agglomeration: a text joins a cluster if it is `sameTopic`
 * with ANY existing member (not just a fixed representative). This is what
 * makes the cap genuinely topic-level on the live evidence: the deletion
 * gap appears as "walk me through the deletion flow", "what artifact
 * confirms deletion completed", "what mechanism prevents deletion". Those
 * outer phrasings share fewer than 2 content words with each other but each
 * shares >= 2 with a bridging phrasing, so single-link collapses the whole
 * family into one cluster while representative-only matching would split it.
 *
 * Single-link can chain unrelated topics if a bridge exists; here the gap
 * subject noun recurs across every phrasing of a gap and the audit data
 * shows distinct gaps share 0 content words, so chaining across gaps does
 * not occur in practice. Texts with no content words are dropped (no
 * identifiable topic).
 */
function clusterTopics(texts: string[]): TopicCluster[] {
  // Keep only texts substantial enough to be a gap topic; each is a node.
  // Thin fragments (below MIN_TOPIC_CONTENT_WORDS) are not re-probeable
  // gaps and are dropped so they never participate in the cap.
  const nodes = texts
    .map(text => ({ text, words: topicContentWords(text) }))
    .filter(n => n.words.size >= MIN_TOPIC_CONTENT_WORDS);

  // Union-find for full transitive closure: a later text that links two
  // earlier sub-clusters MERGES them, which a single greedy pass would miss.
  const parent = nodes.map((_, i) => i);
  const find = (i: number): number => {
    while (parent[i] !== i) {
      parent[i] = parent[parent[i]!]!;
      i = parent[i]!;
    }
    return i;
  };
  const union = (a: number, b: number): void => {
    const ra = find(a), rb = find(b);
    if (ra !== rb) parent[Math.max(ra, rb)] = Math.min(ra, rb);
  };
  for (let i = 0; i < nodes.length; i++) {
    for (let j = i + 1; j < nodes.length; j++) {
      if (sameTopic(nodes[i]!.words, nodes[j]!.words)) union(i, j);
    }
  }

  // Collect members per root, preserving first-seen order for the rep.
  const byRoot = new Map<number, TopicCluster>();
  for (let i = 0; i < nodes.length; i++) {
    const root = find(i);
    let cluster = byRoot.get(root);
    if (!cluster) {
      cluster = { rep: nodes[root]!.text, members: [] };
      byRoot.set(root, cluster);
    }
    cluster.members.push(nodes[i]!.words);
  }
  return [...byRoot.values()];
}

/**
 * AAP-146 - how many PRIOR asked follow-up questions belong to the same gap
 * topic as the candidate. Single-link: the candidate counts a prior ask if
 * it is `sameTopic` with that ask OR with any other prior ask transitively
 * linked to it. This is the deterministic, cross-question gap-topic ledger
 * the cap reads from.
 *
 * `priorFollowUpTexts` is the list of follow-up question texts already
 * ASKED this session, in order. We deliberately compare against asked
 * follow-ups only (not core questions): the cap governs how often a GAP is
 * re-probed, and core questions are the fixed bank, not gap probes. The
 * count is cross-question by construction: a deletion probe spawned under
 * `writes` and another spawned under `data` both land in this list and both
 * join the same topic cluster.
 */
export function countPriorAsksForTopic(
  candidateText: string,
  priorFollowUpTexts: string[],
): number {
  const candidate = topicContentWords(candidateText);
  // Below the floor the candidate is not an identifiable gap topic; exempt.
  if (candidate.size < MIN_TOPIC_CONTENT_WORDS) return 0;
  // Cluster the PRIOR asks WITH the candidate appended, so the candidate can
  // act as a bridge that merges two prior sub-clusters that no earlier ask
  // connected. Then return the size of the candidate's cluster minus the
  // candidate itself (the count of PRIOR asks sharing its topic). Without the
  // bridge, varied phrasings that only connect through the candidate would be
  // counted as separate topics and the cap would under-count.
  const clusters = clusterTopics([...priorFollowUpTexts, candidateText]);
  for (const c of clusters) {
    if (c.members.some(m => sameTopic(candidate, m))) {
      // Subtract 1 for the candidate's own membership entry.
      return c.members.length - 1;
    }
  }
  return 0;
}

/**
 * AAP-146 - the set of gap topics already asked the cap number of times,
 * one representative phrasing per topic. Fed to the follow-up-generating
 * LLM as "these gaps are already recorded; do NOT ask about them again".
 * Uses the same single-link clustering as the cap so the prompt list and
 * the deterministic backstop agree on what counts as one topic.
 */
export function gapTopicsAtCap(priorFollowUpTexts: string[]): string[] {
  return clusterTopics(priorFollowUpTexts)
    .filter(c => c.members.length >= MAX_GAP_TOPIC_ASKS)
    .map(c => c.rep);
}

/**
 * AAP-146 - pull the follow-up question texts out of a transcript: every
 * entry whose question text does NOT match a core question exactly is an
 * LLM-generated follow-up (adversarial probe or vagueness follow-up). This
 * is the same core-vs-follow-up test the planner uses during rehydration,
 * which is why the ledger reconstructs identically after a restart.
 */
function followUpTextsFromTranscript(transcript: QAPair[]): string[] {
  const coreTexts = new Set<string>(CORE_QUESTIONS.map(c => c.text));
  return transcript
    .filter(qa => !coreTexts.has(qa.question))
    .map(qa => qa.question);
}

// ─── Protocol factory ────────────────────────────────────────────────────────

/**
 * Build an InterviewProtocol.
 *
 * AAP-71: `maxFollowUps` is now an OPTIONAL hard ceiling. Default
 * (undefined) disables the global cap entirely; the per-question cap of 2
 * is the only production limit. Tests use `maxFollowUps: 0` to disable
 * LLM-driven follow-ups deterministically. Any positive integer acts as
 * a session-wide ceiling on regular follow-ups (adversarial probes are
 * tracked separately and never consume this budget).
 */
export function createProtocol(llmClient: LLMClient, maxFollowUps?: number): InterviewProtocol {
  const coreQuestions = getAllQuestionsSorted();
  let currentIndex = 0;
  const transcript: QAPair[] = [];
  // AAP-71: `followUpIdCounter` is a monotonic counter used ONLY to
  // mint unique follow-up question IDs. It is no longer gated on
  // `maxFollowUps`; the production limit is the per-question cap of 2.
  // Adversarial probes have their own counter (`adversarialProbeCount`)
  // and do not increment this one, so they don't consume the optional
  // `maxFollowUps` ceiling either.
  let followUpIdCounter = 0;
  const followUpCountPerQuestion = new Map<string, number>();
  // AAP-43 P3 #10/#11: limit adversarial probes per session so the
  // conversation doesn't devolve into interrogation.
  let adversarialProbeCount = 0;
  const MAX_ADVERSARIAL_PROBES = 2;
  const probedClaimKinds = new Set<string>();
  let repeatedAnswerCount = 0;

  // Follow-up queue
  const followUpQueue: InterviewQuestion[] = [];

  return {
    totalCoreQuestions: coreQuestions.length,

    nextQuestion(): InterviewQuestion | null {
      // Drain follow-up queue first
      if (followUpQueue.length > 0) {
        return followUpQueue.shift()!;
      }

      if (currentIndex >= coreQuestions.length) {
        return null;
      }

      return coreQuestions[currentIndex++];
    },

    recordAnswer(question: InterviewQuestion, answer: string): boolean {
      // Skip greetings — don't record them as answers
      if (transcript.length === 0 && isGreeting(answer)) {
        // Don't rewind currentIndex — SessionManager will re-ask pendingQuestion directly
        return false;
      }

      // Detect stale answers from a lost/different session
      if (isStaleAnswer(question, answer)) {
        // Don't rewind — SessionManager will re-ask pendingQuestion directly
        return false;
      }

      // Detect repeated/canned answers
      if (isRepeatedAnswer(answer, transcript)) {
        repeatedAnswerCount++;
        // Still record it (for transparency in transcript) but mark the category
        transcript.push({
          question: question.text,
          answer: `[REPEATED RESPONSE] ${answer}`,
          category: question.category,
        });
        // After 3+ repeats, stop generating follow-ups — agent is stuck
        return true;
      }

      transcript.push({
        question: question.text,
        answer,
        category: question.category,
      });
      return true;
    },

    async generateFollowUp(category: QAPair['category']): Promise<InterviewQuestion | null> {
      // Per-question cap (2 follow-ups per core question). This is the
      // primary production limit on follow-ups. Adversarial probes also
      // count against this cap (per AAP-71 design) so a single core
      // question can never receive more than 2 follow-ups regardless of
      // type.
      //
      // AAP-77: must attribute to the MOST RECENT core question in this
      // category, not the first one declared. Categories like `data`,
      // `access`, `writes`, and `purpose` have multiple core questions;
      // `find()` over `coreQuestions` returns the first declared, while
      // `primeFollowUpCounts` (and the increment below) attribute to the
      // most-recently-asked core. With mismatched IDs the counter never
      // reaches 2 and the cap never fires. Scanning the transcript
      // backward keeps the cap check and the increment writing to the
      // same key.
      const lastCoreQ = findMostRecentCoreInCategory(category, transcript, coreQuestions);
      if (lastCoreQ) {
        const count = followUpCountPerQuestion.get(lastCoreQ.id) ?? 0;
        if (count >= 2) return null;
      }

      // Don't follow up if agent is repeating canned responses
      if (repeatedAnswerCount >= 3) return null;

      const categoryQA = transcript.filter(qa => qa.category === category);
      if (categoryQA.length === 0) return null;

      // Check if the last answer was vague
      const lastAnswer = categoryQA[categoryQA.length - 1].answer;
      const vague = isVagueAnswer(lastAnswer);

      // Find missing compliance fields across all transcript
      const missingFields = findMissingFields(transcript);

      // AAP-43 P3: scan recent answers for adversarial-claim opportunities
      // (HITL, narrow-scope claim, monitored, deletion policy, etc.). If
      // one is detected and we haven't exhausted the per-session budget,
      // prefer an adversarial probe over a generic vagueness follow-up.
      const recentText = transcript.slice(-4).map((qa) => qa.answer).join(' \n ');
      const adversarialClaim =
        adversarialProbeCount < MAX_ADVERSARIAL_PROBES
          ? detectAdversarialClaim(recentText)
          : null;
      const isNewClaim = adversarialClaim !== null && !probedClaimKinds.has(adversarialClaim.kind);

      // Only generate follow-up if answer was vague, fields are missing,
      // or a new adversarial claim was detected
      if (!vague && missingFields.length === 0 && !isNewClaim) return null;

      // AAP-71: optional hard ceiling on regular (non-adversarial)
      // follow-ups. `undefined` = no cap (production default). Tests use
      // `0` to disable LLM-driven follow-up generation entirely.
      // Adversarial probes are NOT gated on this ceiling: they have
      // their own `MAX_ADVERSARIAL_PROBES = 2` limit (checked above).
      if (
        !isNewClaim &&
        typeof maxFollowUps === 'number' &&
        followUpIdCounter >= maxFollowUps
      ) {
        return null;
      }

      // AAP-146 - gap topics already asked the cap number of times this
      // session. Fed to the prompt so the LLM is told up front not to
      // re-probe them, and used below as the deterministic backstop if it
      // does anyway.
      const priorFollowUpTexts = followUpTextsFromTranscript(transcript);
      const atCapTopics = gapTopicsAtCap(priorFollowUpTexts);

      try {
        const prompt =
          isNewClaim && adversarialClaim
            ? buildAdversarialProbePrompt(adversarialClaim.kind, adversarialClaim.probe, categoryQA, atCapTopics)
            : buildFollowUpPrompt(
                category,
                categoryQA,
                missingFields.length > 0 ? missingFields : undefined,
                atCapTopics,
              );

        const followUpText = await llmClient.chat(INTERVIEW_SYSTEM_PROMPT, prompt);

        if (!followUpText.trim()) return null;

        // AAP-146 - deterministic session-level gap-topic cap. If this
        // candidate re-probes a gap that has already been asked
        // MAX_GAP_TOPIC_ASKS times (cross-question: a deletion probe under
        // `writes` and another under `data` both count toward one topic),
        // drop it. The gap stands as recorded; it still reaches findings
        // via the normal analysis path. We must NOT have bumped any cap
        // counter yet (the increments happen below) so dropping here
        // leaves the per-question and ID counters untouched.
        if (countPriorAsksForTopic(followUpText.trim(), priorFollowUpTexts) >= MAX_GAP_TOPIC_ASKS) {
          return null;
        }

        // Bump per-question cap counter for every follow-up (regular and
        // adversarial). Bump the global ID counter only for regular
        // follow-ups. Adversarial probes use their own counter for IDs
        // and must not consume the optional `maxFollowUps` ceiling.
        if (lastCoreQ) {
          followUpCountPerQuestion.set(lastCoreQ.id, (followUpCountPerQuestion.get(lastCoreQ.id) ?? 0) + 1);
        }
        let idSuffix: number;
        if (isNewClaim && adversarialClaim) {
          adversarialProbeCount++;
          probedClaimKinds.add(adversarialClaim.kind);
          idSuffix = adversarialProbeCount;
        } else {
          followUpIdCounter++;
          idSuffix = followUpIdCounter;
        }

        const idPrefix = isNewClaim && adversarialClaim ? `probe_${adversarialClaim.kind}` : `followup_${category}`;
        const followUp: InterviewQuestion = {
          id: `${idPrefix}_${idSuffix}`,
          category,
          text: followUpText.trim(),
          priority: 100 + followUpIdCounter + adversarialProbeCount,
        };
        return followUp;
      } catch {
        return null;
      }
    },

    getTranscript(): QAPair[] {
      return [...transcript];
    },

    isComplete(): boolean {
      return currentIndex >= coreQuestions.length && followUpQueue.length === 0;
    },

    primeFollowUpCounts(state: { global: number; perQuestion: Map<string, number> }): void {
      // Clamp negative inputs to zero and trust the caller's count
      // otherwise. The per-question cap check (`count >= 2`) uses `>=`,
      // so honest counts work directly and over-counts are still safe
      // (just slightly more conservative). The `global` field now seeds
      // the `followUpIdCounter` so re-minted follow-up IDs after
      // rehydration stay unique relative to anything the prior protocol
      // instance produced. AAP-71: the global cap was removed, so
      // `state.global` no longer participates in any gating check.
      followUpIdCounter = Math.max(0, state.global | 0);
      for (const [qid, count] of state.perQuestion) {
        followUpCountPerQuestion.set(qid, Math.max(0, count | 0));
      }
    },
  };
}

/**
 * Enqueue a follow-up question to be asked next.
 * Used by SessionManager to avoid monkey-patching protocol.nextQuestion.
 */
export function enqueueFollowUp(protocol: InterviewProtocol, followUp: InterviewQuestion): void {
  // The follow-up queue is internal to createProtocol, so we need another approach.
  // Instead, we expose a method to push into the queue via the protocol's nextQuestion behavior.
  // Actually, the clean way is to just have SessionManager track its own queue — see sessions.ts.
  // This function exists for the scan/CLI path where the interviewer handles follow-ups inline.
  void protocol;
  void followUp;
}
